/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.io.*;
import java.net.Socket;
import javax.swing.*;
import java.awt.*;
import Kandidat.Kandidat;
import java.util.logging.Level;
import java.util.logging.Logger;
/**
 *
 * @author HP
 */
public class Voter3 extends javax.swing.JFrame {
    Kandidat[] listKandidat;
    JPanel pnlResultColl;
    Socket connection;
    ObjectInputStream fromServer;
    ObjectOutputStream toServer;
    /**
     * Creates new form Voter3
     * @param nama
     * @param connection
     * @param fromServer
     * @param toServer
     */
    @SuppressWarnings("OverridableMethodCallInConstructor")
    public Voter3(String nama, 
                  Socket connection, 
                  ObjectInputStream fromServer, 
                  ObjectOutputStream toServer) {
        this.connection = connection;
        this.fromServer = fromServer;
        this.toServer = toServer;
        
        //Show Form
        showForm();
        jLabel2.setText(nama);
        
        //Fetch kandidat data from server
        EventQueue.invokeLater(() -> {
            try {
                this.listKandidat = (Kandidat[]) fromServer.readObject();
                constructComp();
                jScrollPane2.setViewportView(this.pnlResultColl);
            }catch (IOException | ClassNotFoundException ex) {
                Logger.getLogger(Voter2.class.getName()).log(Level.SEVERE, null, ex);
            }
        });
    }
    
    public void showForm(){
        initComponents();
        this.setLocationRelativeTo(null);
        this.setVisible(true);
    }
    
    public void constructComp(){
        this.pnlResultColl = new JPanel();
        this.pnlResultColl.setLayout(new BoxLayout(this.pnlResultColl, BoxLayout.Y_AXIS));
        
        if(this.listKandidat != null){
            for(Kandidat calon : this.listKandidat){
                String namaKandidat = calon.getNama();
                
                JPanel pnl_vote = new JPanel();
                pnl_vote.setSize(384, 14);
                pnl_vote.setBorder(BorderFactory.createMatteBorder(0, 0, 2, 0, Color.LIGHT_GRAY));
                GridBagLayout gridbag = new GridBagLayout();
                GridBagConstraints cons = new GridBagConstraints();
                pnl_vote.setLayout(gridbag);
                
                cons.gridwidth = GridBagConstraints.RELATIVE;
                cons.weightx = 2.0;
                JLabel lbl_nama = new JLabel(namaKandidat);
                gridbag.setConstraints(lbl_nama, cons);
                pnl_vote.add(lbl_nama);
                
                cons.gridwidth = GridBagConstraints.REMAINDER;
                cons.weightx = 1.0;
                JLabel lbl_suara = new JLabel(String.valueOf(calon.getJumlahSuara()));
                gridbag.setConstraints(lbl_suara, cons);
                pnl_vote.add(lbl_suara);
                
                this.pnlResultColl.add(pnl_vote);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Kamu Memilh : ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Voter3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Voter3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Voter3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Voter3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>


    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
